spam = "Hello World"
print(spam.upper())
print(spam.lower())
print(spam.upper().isupper())
print(spam.lower().islower())
print("hello".isalpha())
print("hello123".isalpha())
print("hello123".isalnum())
print("hello".isalnum())
print("123".isdecimal())
print("  ".isspace())
print("This Is Title Case".istitle())
print("This Is Title Case 123".istitle())
print("This Is not Title Case".istitle())
print("This Is NOT Title Case Either".istitle())
